### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by baoshan** [eliasm307/monaco-editor-typescript-locales#4]
Hi, @eliasm307,

Thanks so much for providing a read-to-use solution to make _language locale_ customizable! 🥇 

I think there may be some small issues in the publishing process:

```
> require("monaco-editor-typescript-locales")
/Users/baoshan/Projects/metl/node_modules/monaco-editor-typescript-locales/dist/index.js:25
export function register(monaco) {
^^^^^^

Uncaught SyntaxError: Unexpected token 'export'
```

Also the `index.d.ts` file [is not published](https://www.npmjs.com/package/monaco-editor-typescript-locales?activeTab=code).

Maybe we need to set `"module": "commonjs"` in `tsconfig.json`? Also, are you open to a PR?

**Comment by eliasm307** [comment]
Hi @baoshan, thanks for raising this. Yes, i overlooked commonjs support.

So to fix this, instead of making the package commonjs, I think this should have conditional exports, ie https://nodejs.org/api/packages.html#conditional-exports

So this means creating 2 builds, 1 for esm and 1 for commonjs and defining the entry points as the conditional exports depending on the usage.

If you want to raise a PR you are welcome, but let me know if you can't and I'll work on this

**Comment by baoshan** [comment]
Thanks for your reply!

I would like to save you some minutes and create a PR (using _conditional exports_) later today.
